# Generated by Django 5.1 on 2024-09-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_tag_caption_alter_tag_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='blog_slug'),
        ),
    ]
