# Generated by Django 5.1 on 2024-10-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('password', models.BigIntegerField(verbose_name='password')),
            ],
            options={
                'verbose_name': 'credential',
                'verbose_name_plural': 'credentials',
            },
        ),
    ]
